### ISSUE TITLE
Request for Username "langx" - Contribution Request

### ISSUE THREAD

**Issue by xuelink** [langx/cepix#2]
Dear @egetzel and @dcsan

I trust this message finds you both well. I'm reaching out to discuss the possibility of securing the username "langx" on your platform. This username holds significant relevance to both my personal and professional endeavors, and I believe its acquisition would greatly enhance my online presence.

Allow me to share why this username is of utmost importance to me:

1. **Relevance to Language and Communication**: "langx" epitomizes the essence of language, which is a cornerstone of my life's work. As an avid language enthusiast deeply immersed in linguistic pursuits, this username resonates profoundly with my passion for language learning, communication, and fostering cross-cultural exchange.

2. **Professional Identity**: Acquiring the username "langx" seamlessly aligns with my professional identity. Consistency across various online platforms is pivotal for establishing credibility and recognition within my field. By adopting "langx" as my username, I aim to consolidate my online presence and enhance my professional visibility.

3. **Brand Cohesion**: As I continue to cultivate my personal brand, maintaining coherence across different digital platforms is paramount. "langx" serves as a succinct and memorable identifier, facilitating brand cohesion and enabling seamless engagement with followers, colleagues, and potential collaborators.

In light of these considerations, I kindly request your assistance in acquiring the username "langx" on your platform. I understand that username availability is contingent on various factors, and I am fully prepared to adhere to any necessary procedures or requirements to secure this username.

Should the username "langx" already be in use, I would greatly appreciate your guidance or assistance in facilitating a username transfer or exploring alternative solutions to achieve my objective.

Furthermore, I would like to take this opportunity to introduce you to our free and open-source app, LangX:

- **Website**: [LangX.io](https://langx.io/)
- **Apps**: [iOS](https://apps.apple.com/us/app/langx-practice-learn-succeed/id6474187141), [Android](https://play.google.com/store/apps/details?id=tech.newchapter.languageXchange), [Web App](https://app.languagexchange.net/)
- **Token**: [Website](https://token.langx.io/), [Twitter](https://twitter.com/langx_token), [Whitepaper](https://app.gitbook.com/invite/0n6eGkPoppmsyoZuw2GO/I9eV3C08ufDq2xWLjeVn)
- **Insights**: [Insight Dashboard](https://insight.langx.io)
- **Discord**: [Discord](https://discord.langx.io/)
- **Status Page**: [Status](https://status.langx.io/)
- **GitHub**: [Repository](https://github.com/langxapp), [Release Notes](https://github.com/langxapp/langx/releases), [Issues](https://github.com/langxapp/langx/issues), [Backlog](https://backlog.langx.io/)
- **Social Media**: [Twitter](https://twitter.com/langx_app), [Telegram](https://t.me/langxapp), [Instagram](https://www.instagram.com/langxapp), [Facebook](https://www.facebook.com/langxapp), [TikTok](https://www.tiktok.com/@langxapp), [YouTube](https://www.youtube.com/@langxapp), [Bluesky](https://bsky.app/profile/langx.io), [LinkedIn](https://www.linkedin.com/products/new-chapter-technology-limited-liability-company-languagexchange-practice-learn-succeed/)

I genuinely appreciate your consideration of my request and eagerly anticipate your response. Thank you for your time and attention.

Warm regards,

**Comment by dcsan** [comment]
hi @xuelink impressive project you have.
transfer maybe possible, but your profile is pretty anon?

**Comment by xuelink** [comment]
> transfer maybe possible, but your profile is pretty anon?

Yea, if you need KYC before to do it, let me DM in discord, we can complete these required steps ahah :D
